package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * Currency generated by hbm2java
 */
public class Currency  implements java.io.Serializable {


     private int currencyId;
     private String currencyName;
     private Double currencyRate;

    public Currency() {
    }

	
    public Currency(int currencyId, String currencyName) {
        this.currencyId = currencyId;
        this.currencyName = currencyName;
    }
    public Currency(int currencyId, String currencyName, Double currencyRate) {
       this.currencyId = currencyId;
       this.currencyName = currencyName;
       this.currencyRate = currencyRate;
    }
   
    public int getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(int currencyId) {
        this.currencyId = currencyId;
    }
    public String getCurrencyName() {
        return this.currencyName;
    }
    
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }
    public Double getCurrencyRate() {
        return this.currencyRate;
    }
    
    public void setCurrencyRate(Double currencyRate) {
        this.currencyRate = currencyRate;
    }




}


