package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * Matching generated by hbm2java
 */
public class Matching  implements java.io.Serializable {


     private String it4prifitArticleName;
     private long supplierId;
     private String supplierArticleName;

    public Matching() {
    }

    public Matching(String it4prifitArticleName, long supplierId, String supplierArticleName) {
       this.it4prifitArticleName = it4prifitArticleName;
       this.supplierId = supplierId;
       this.supplierArticleName = supplierArticleName;
    }
   
    public String getIt4prifitArticleName() {
        return this.it4prifitArticleName;
    }
    
    public void setIt4prifitArticleName(String it4prifitArticleName) {
        this.it4prifitArticleName = it4prifitArticleName;
    }
    public long getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }
    public String getSupplierArticleName() {
        return this.supplierArticleName;
    }
    
    public void setSupplierArticleName(String supplierArticleName) {
        this.supplierArticleName = supplierArticleName;
    }




}


