package Pojo;
// Generated 15.09.2009 22:16:12 by Hibernate Tools 3.2.1.GA



/**
 * Nixdata generated by hbm2java
 */
public class Nixdata  implements java.io.Serializable {


     private long id;
     private String fullName;
     private String manufacturer;
     private String article;
     private String productType;
     private String pictureUrl;
     private String groupe;
     private String attribute;
     private String attributeValue;

    public Nixdata() {
    }

	
    public Nixdata(long id) {
        this.id = id;
    }
    public Nixdata(long id, String fullName, String manufacturer, String article, String productType, String pictureUrl, String groupe, String attribute, String attributeValue) {
       this.id = id;
       this.fullName = fullName;
       this.manufacturer = manufacturer;
       this.article = article;
       this.productType = productType;
       this.pictureUrl = pictureUrl;
       this.groupe = groupe;
       this.attribute = attribute;
       this.attributeValue = attributeValue;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getPictureUrl() {
        return this.pictureUrl;
    }
    
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }
    public String getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(String groupe) {
        this.groupe = groupe;
    }
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }




}


