package Pojo;
// Generated 28.09.2009 12:16:38 by Hibernate Tools 3.2.1.GA



/**
 * Processes generated by hbm2java
 */
public class Processes  implements java.io.Serializable {


     private long id;
     private String processName;
     private Boolean processStatus;

    public Processes() {
    }

	
    public Processes(long id) {
        this.id = id;
    }
    public Processes(long id, String processName, Boolean processStatus) {
       this.id = id;
       this.processName = processName;
       this.processStatus = processStatus;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }
    public Boolean getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(Boolean processStatus) {
        this.processStatus = processStatus;
    }




}


