package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private long productTypeId, id;
     private String productTypeName;

    public ProductType() {
    }

    public ProductType(long productTypeId) {
        this.productTypeId = productTypeId;
    }

    public ProductType(long productTypeId, String productTypeName) {
       this.productTypeId = productTypeId;
       this.productTypeName = productTypeName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public ProductType(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    
   
    public long getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(long productTypeId) {
        this.productTypeId = productTypeId;
    }
    public String getProductTypeName() {
        return this.productTypeName;
    }
    
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }




}


