package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private long shopId;
     private String shopName;

    public Shop() {
    }

    public Shop(long shopId, String shopName) {
       this.shopId = shopId;
       this.shopName = shopName;
    }
   
    public long getShopId() {
        return this.shopId;
    }
    
    public void setShopId(long shopId) {
        this.shopId = shopId;
    }
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }




}


