package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

    private long supplierId;
    private String supplierName;

    public Supplier(String supplierName) {
        this.supplierName = supplierName;
    }

    public Supplier() {
    }

    public Supplier(long supplierId, String supplierName) {
        this.supplierId = supplierId;
        this.supplierName = supplierName;
    }

    public long getSupplierId() {
        return this.supplierId;
    }

    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return this.supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
}


