package Pojo;
// Generated 06.10.2009 11:06:51 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer categoriesId;
     private String categoriesImage;
     private int parentId;
     private Integer sortOrder;
     private Date dateAdded;
     private Date lastModified;
     private boolean categoriesStatus;

    public Categories() {
    }

	
    public Categories(int parentId, boolean categoriesStatus) {
        this.parentId = parentId;
        this.categoriesStatus = categoriesStatus;
    }
    public Categories(String categoriesImage, int parentId, Integer sortOrder, Date dateAdded, Date lastModified, boolean categoriesStatus) {
       this.categoriesImage = categoriesImage;
       this.parentId = parentId;
       this.sortOrder = sortOrder;
       this.dateAdded = dateAdded;
       this.lastModified = lastModified;
       this.categoriesStatus = categoriesStatus;
    }
   
    public Integer getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(Integer categoriesId) {
        this.categoriesId = categoriesId;
    }
    public String getCategoriesImage() {
        return this.categoriesImage;
    }
    
    public void setCategoriesImage(String categoriesImage) {
        this.categoriesImage = categoriesImage;
    }
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }
    public Integer getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    public boolean isCategoriesStatus() {
        return this.categoriesStatus;
    }
    
    public void setCategoriesStatus(boolean categoriesStatus) {
        this.categoriesStatus = categoriesStatus;
    }




}


