package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * It4articles generated by hbm2java
 */
public class It4articles  implements java.io.Serializable {


     private String it4prifitArticleName;
     private Long it4prifitArticleClasscat;
     private String it4prifitArticleDescription;
     private long manufacturerId;
     private long productTypeId;
     private Double fixedPrice;
     private Boolean fixed;
     private Integer quantity;
     private Integer availableStatus;

    public It4articles() {
    }

	
    public It4articles(String it4prifitArticleName, long manufacturerId, long productTypeId) {
        this.it4prifitArticleName = it4prifitArticleName;
        this.manufacturerId = manufacturerId;
        this.productTypeId = productTypeId;
    }
    public It4articles(String it4prifitArticleName, Long it4prifitArticleClasscat, String it4prifitArticleDescription, long manufacturerId, long productTypeId, Double fixedPrice, Boolean fixed, Integer quantity, Integer availableStatus) {
       this.it4prifitArticleName = it4prifitArticleName;
       this.it4prifitArticleClasscat = it4prifitArticleClasscat;
       this.it4prifitArticleDescription = it4prifitArticleDescription;
       this.manufacturerId = manufacturerId;
       this.productTypeId = productTypeId;
       this.fixedPrice = fixedPrice;
       this.fixed = fixed;
       this.quantity = quantity;
       this.availableStatus = availableStatus;
    }
   
    public String getIt4prifitArticleName() {
        return this.it4prifitArticleName;
    }
    
    public void setIt4prifitArticleName(String it4prifitArticleName) {
        this.it4prifitArticleName = it4prifitArticleName;
    }
    public Long getIt4prifitArticleClasscat() {
        return this.it4prifitArticleClasscat;
    }
    
    public void setIt4prifitArticleClasscat(Long it4prifitArticleClasscat) {
        this.it4prifitArticleClasscat = it4prifitArticleClasscat;
    }
    public String getIt4prifitArticleDescription() {
        return this.it4prifitArticleDescription;
    }
    
    public void setIt4prifitArticleDescription(String it4prifitArticleDescription) {
        this.it4prifitArticleDescription = it4prifitArticleDescription;
    }
    public long getManufacturerId() {
        return this.manufacturerId;
    }
    
    public void setManufacturerId(long manufacturerId) {
        this.manufacturerId = manufacturerId;
    }
    public long getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(long productTypeId) {
        this.productTypeId = productTypeId;
    }
    public Double getFixedPrice() {
        return this.fixedPrice;
    }
    
    public void setFixedPrice(Double fixedPrice) {
        this.fixedPrice = fixedPrice;
    }
    public Boolean getFixed() {
        return this.fixed;
    }
    
    public void setFixed(Boolean fixed) {
        this.fixed = fixed;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getAvailableStatus() {
        return this.availableStatus;
    }
    
    public void setAvailableStatus(Integer availableStatus) {
        this.availableStatus = availableStatus;
    }




}


