package Pojo;
// Generated 09.10.2009 15:37:19 by Hibernate Tools 3.2.1.GA



/**
 * PcProductTypes generated by hbm2java
 */
public class PcProductTypes  implements java.io.Serializable {


     private Integer ptId;
     private String ptName;
     private boolean status;

    public PcProductTypes() {
    }

	
    public PcProductTypes(boolean status) {
        this.status = status;
    }
    public PcProductTypes(String ptName, boolean status) {
       this.ptName = ptName;
       this.status = status;
    }
   
    public Integer getPtId() {
        return this.ptId;
    }
    
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }
    public String getPtName() {
        return this.ptName;
    }
    
    public void setPtName(String ptName) {
        this.ptName = ptName;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


