package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA



/**
 * Pricerule generated by hbm2java
 */
public class Pricerule  implements java.io.Serializable {


     private int priceRuleId;
     private String priceRuleName;

    public Pricerule() {
    }

    public Pricerule(int priceRuleId, String priceRuleName) {
       this.priceRuleId = priceRuleId;
       this.priceRuleName = priceRuleName;
    }
   
    public int getPriceRuleId() {
        return this.priceRuleId;
    }
    
    public void setPriceRuleId(int priceRuleId) {
        this.priceRuleId = priceRuleId;
    }
    public String getPriceRuleName() {
        return this.priceRuleName;
    }
    
    public void setPriceRuleName(String priceRuleName) {
        this.priceRuleName = priceRuleName;
    }




}


