package Pojo;
// Generated 02.09.2009 10:24:26 by Hibernate Tools 3.2.1.GA

/**
 * Supplierprice generated by hbm2java
 */
public class Supplierprice implements java.io.Serializable {

    private long id;
    private long supplierId;
    private String supplierArticleName;
    private String supplierArticleDescription;
    private Double supplierArticlePrice;
    private Integer currencyId;

    public Supplierprice() {
    }

    public Supplierprice(long supplierId, String supplierArticleName, String supplierArticleDescription, Double supplierArticlePrice, Integer currencyId) {
        this.supplierId = supplierId;
        this.supplierArticleName = supplierArticleName;
        this.supplierArticleDescription = supplierArticleDescription;
        this.supplierArticlePrice = supplierArticlePrice;
        this.currencyId = currencyId;
    }

    public Supplierprice(long id, long supplierId, String supplierArticleName) {
        this.id = id;
        this.supplierId = supplierId;
        this.supplierArticleName = supplierArticleName;
    }

    public Supplierprice(long id, long supplierId, String supplierArticleName, String supplierArticleDescription, Double supplierArticlePrice, Integer currencyId) {
        this.id = id;
        this.supplierId = supplierId;
        this.supplierArticleName = supplierArticleName;
        this.supplierArticleDescription = supplierArticleDescription;
        this.supplierArticlePrice = supplierArticlePrice;
        this.currencyId = currencyId;
    }

    public long getId() {
        return this.id;
    }
 
    public void setId(long id) {
        this.id = id;
    }

    public long getSupplierId() {
        return this.supplierId;
    }

    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplierArticleName() {
        return this.supplierArticleName;
    }

    public void setSupplierArticleName(String supplierArticleName) {
        this.supplierArticleName = supplierArticleName;
    }

    public String getSupplierArticleDescription() {
        return this.supplierArticleDescription;
    }

    public void setSupplierArticleDescription(String supplierArticleDescription) {
        this.supplierArticleDescription = supplierArticleDescription;
    }

    public Double getSupplierArticlePrice() {
        return this.supplierArticlePrice;
    }

    public void setSupplierArticlePrice(Double supplierArticlePrice) {
        this.supplierArticlePrice = supplierArticlePrice;
    }

    public Integer getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }
}


