package Pojo;
// Generated 15.09.2009 22:16:12 by Hibernate Tools 3.2.1.GA



/**
 * Nixlinks generated by hbm2java
 */
public class Nixlinks  implements java.io.Serializable {


     private long id;
     private String productType;
     private String productUrl;

    public Nixlinks() {
    }

	
    public Nixlinks(long id) {
        this.id = id;
    }
    public Nixlinks(long id, String productType, String productUrl) {
       this.id = id;
       this.productType = productType;
       this.productUrl = productUrl;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getProductUrl() {
        return this.productUrl;
    }
    
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }




}


