package imf.core.entity;
// Generated 16.11.2010 22:43:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "attribute", catalog = "imf"
)
public class Attribute implements java.io.Serializable {


    private Long id;
    private UnitsGroup unitsGroup;
    private SubsGroup subsGroup;
    private UnitOfMeasure unitOfMeasure;
    private String name;
    private String comment;
    private byte type;
    private Byte typeOfValues;
    private Set attribute2Groupes = new HashSet(0);

    public Attribute() {
    }


    public Attribute(String name, byte type) {
        this.name = name;
        this.type = type;
    }

    public Attribute(UnitsGroup unitsGroup, SubsGroup subsGroup, UnitOfMeasure unitOfMeasure, String name, String comment, byte type, Byte typeOfValues, Set attribute2Groupes) {
        this.unitsGroup = unitsGroup;
        this.subsGroup = subsGroup;
        this.unitOfMeasure = unitOfMeasure;
        this.name = name;
        this.comment = comment;
        this.type = type;
        this.typeOfValues = typeOfValues;
        this.attribute2Groupes = attribute2Groupes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = UnitsGroup.class)
    @JoinColumn(name = "unit_groupe_id")
    public UnitsGroup getUnitsGroupe() {
        return this.unitsGroup;
    }

    public void setUnitsGroupe(UnitsGroup unitsGroup) {
        this.unitsGroup = unitsGroup;
    }

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = SubsGroup.class)
    @JoinColumn(name = "subs_groupe_id")
    public SubsGroup getSubsGroupe() {
        return this.subsGroup;
    }

    public void setSubsGroupe(SubsGroup subsGroup) {
        this.subsGroup = subsGroup;
    }

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = UnitOfMeasure.class)
    @JoinColumn(name = "unit_id")
    public UnitOfMeasure getUnitOfMeasure() {
        return this.unitOfMeasure;
    }

    public void setUnitOfMeasure(UnitOfMeasure unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }

    @Column(name = "name", nullable = false, length = 512)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "comment", length = 1024)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "type", nullable = false)
    public byte getType() {
        return this.type;
    }

    public void setType(byte type) {
        this.type = type;
    }

    @Column(name = "type_of_values")
    public Byte getTypeOfValues() {
        return this.typeOfValues;
    }

    public void setTypeOfValues(Byte typeOfValues) {
        this.typeOfValues = typeOfValues;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "attribute")
    public Set getAttribute2Groupes() {
        return this.attribute2Groupes;
    }

    public void setAttribute2Groupes(Set attribute2Groupes) {
        this.attribute2Groupes = attribute2Groupes;
    }


}


