package imf.core.entity;
// Generated 16.11.2010 22:43:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeatureBenefit generated by hbm2java
 */
@Entity
@Table(name = "feature_benefit", catalog = "imf"
)
public class FeatureBenefit implements java.io.Serializable {


    private Long id;
    private String feature;
    private String benefit;
    private Integer weight;
    private Set bisinessModels = new HashSet(0);

    public FeatureBenefit() {
    }

    public FeatureBenefit(String feature, String benefit, Integer weight, Set bisinessModels) {
        this.feature = feature;
        this.benefit = benefit;
        this.weight = weight;
        this.bisinessModels = bisinessModels;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "feature", length = 1024)
    public String getFeature() {
        return this.feature;
    }

    public void setFeature(String feature) {
        this.feature = feature;
    }

    @Column(name = "benefit", length = 1024)
    public String getBenefit() {
        return this.benefit;
    }

    public void setBenefit(String benefit) {
        this.benefit = benefit;
    }

    @Column(name = "weight")
    public Integer getWeight() {
        return this.weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "featureBenefit")
    public Set getBisinessModels() {
        return this.bisinessModels;
    }

    public void setBisinessModels(Set bisinessModels) {
        this.bisinessModels = bisinessModels;
    }


}


