package imf.core.entity;
// Generated 16.11.2010 22:43:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "groupe"
        , catalog = "imf"
)
public class Group implements java.io.Serializable {


    private Long id;
    private String name;
    private String comment;
    private Set templates = new HashSet(0);
    private Set attribute2Groupes = new HashSet(0);

    public Group() {
    }


    public Group(String name) {
        this.name = name;
    }

    public Group(String name, String comment, Set templates, Set attribute2Groupes) {
        this.name = name;
        this.comment = comment;
        this.templates = templates;
        this.attribute2Groupes = attribute2Groupes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 512)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "comment", length = 1024)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "groupe_2_template", catalog = "imf", joinColumns = {
            @JoinColumn(name = "groupe_id", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "template_id", nullable = false, updatable = false)})
    public Set getTemplates() {
        return this.templates;
    }

    public void setTemplates(Set templates) {
        this.templates = templates;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "groupe")
    public Set getAttribute2Groupes() {
        return this.attribute2Groupes;
    }

    public void setAttribute2Groupes(Set attribute2Groupes) {
        this.attribute2Groupes = attribute2Groupes;
    }


}


