package imf.core.entity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UnitsGroup generated by hbm2java
 */
@Entity
@Table(name = "units_group")
public class UnitsGroup implements java.io.Serializable {


    private Long id;
    private String name;
    private String comment;
    private List unitOfMeasures = new ArrayList(0);
//    private Set subsGroupes = new HashSet(0);
//    private Set attributes = new HashSet(0);

    public UnitsGroup() {
    }


    public UnitsGroup(String name) {
        this.name = name;
    }

//    public UnitsGroup(String name, String comment, Set unitOfMeasures, Set subsGroupes, Set attributes) {
//        this.name = name;
//        this.comment = comment;
//        this.unitOfMeasures = unitOfMeasures;
////        this.subsGroupes = subsGroupes;
////        this.attributes = attributes;
//    }

    @Id
    @SequenceGenerator(name = "units_group_seq", sequenceName = "units_group_id", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "units_group_seq")
    @Column(name = "id", unique = true, nullable = false)

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 512)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "comment", length = 1024)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "unitsGroupe", targetEntity = UnitOfMeasure.class)
    public List getUnitOfMeasures() {
        return this.unitOfMeasures;
    }

    public void setUnitOfMeasures(List unitOfMeasures) {
        this.unitOfMeasures = unitOfMeasures;
    }

//    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "unitsGroupe", targetEntity = SubsGroup.class)
//    public Set getSubsGroupes() {
//        return this.subsGroupes;
//    }
//
//    public void setSubsGroupes(Set subsGroupes) {
//        this.subsGroupes = subsGroupes;
//    }
//
//    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "unitsGroupe", targetEntity = Attribute.class)
//    public Set getAttributes() {
//        return this.attributes;
//    }
//
//    public void setAttributes(Set attributes) {
//        this.attributes = attributes;
//    }


}


