package pojo;
// Generated 30.09.2010 0:13:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private Integer shopId;
     private String shopName;
     private String shopUrl;
     private String shopComment;
     private Set inputDatas = new HashSet(0);

    public Shop() {
    }

    public Shop(String shopName, String shopUrl, String shopComment, Set inputDatas) {
       this.shopName = shopName;
       this.shopUrl = shopUrl;
       this.shopComment = shopComment;
       this.inputDatas = inputDatas;
    }
   
    public Integer getShopId() {
        return this.shopId;
    }
    
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    public String getShopUrl() {
        return this.shopUrl;
    }
    
    public void setShopUrl(String shopUrl) {
        this.shopUrl = shopUrl;
    }
    public String getShopComment() {
        return this.shopComment;
    }
    
    public void setShopComment(String shopComment) {
        this.shopComment = shopComment;
    }
    public Set getInputDatas() {
        return this.inputDatas;
    }
    
    public void setInputDatas(Set inputDatas) {
        this.inputDatas = inputDatas;
    }




}


