package pojo;
// Generated 16.06.2010 23:40:34 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

    private Integer unitId;
    private String unitName;
    private List<UnitAlternativeName> unitAlternativeNames = new ArrayList(0);

    public Unit() {
    }

    public Unit(String unitName, List unitAlternativeNames) {
        this.unitName = unitName;
        this.unitAlternativeNames = unitAlternativeNames;
    }

    public Integer getUnitId() {
        return this.unitId;
    }

    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    public String getUnitName() {
        return this.unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public List getUnitAlternativeNames() {
        return this.unitAlternativeNames;
    }

    public void setUnitAlternativeNames(List unitAlternativeNames) {
        this.unitAlternativeNames = unitAlternativeNames;
    }
}
