package pojo;
// Generated 16.06.2010 23:40:34 by Hibernate Tools 3.2.1.GA

/**
 * UnitAlternativeName generated by hbm2java
 */
public class UnitAlternativeName implements java.io.Serializable {

    private Integer unitAlternativeNameId;
    private Unit unit;
    private String unitAlternativeNameValue;

    public UnitAlternativeName() {
    }

    public UnitAlternativeName(Integer unitAlternativeNameId) {
        this.unitAlternativeNameId = unitAlternativeNameId;
    }

    public UnitAlternativeName(Integer unitAlternativeNameId, Unit unit) {
        this.unitAlternativeNameId = unitAlternativeNameId;
        this.unit = unit;
    }

    public UnitAlternativeName(Integer unitAlternativeNameId, Unit unit, String unitAlternativeNameValue) {
        this.unitAlternativeNameId = unitAlternativeNameId;
        this.unit = unit;
        this.unitAlternativeNameValue = unitAlternativeNameValue;
    }

    public Unit getUnit() {
        return unit;
    }

    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    public Integer getUnitAlternativeNameId() {
        return unitAlternativeNameId;
    }

    public void setUnitAlternativeNameId(Integer unitAlternativeNameId) {
        this.unitAlternativeNameId = unitAlternativeNameId;
    }

    public String getUnitAlternativeNameValue() {
        return unitAlternativeNameValue;
    }

    public void setUnitAlternativeNameValue(String unitAlternativeNameValue) {
        this.unitAlternativeNameValue = unitAlternativeNameValue;
    }
}
