package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

    private Integer articleId;
    private Bank bank;
    private String articleName;
    private Set matchingsForArticleIdFrom = new HashSet(0);
    private Set matchingsForArticleIdTo = new HashSet(0);
    private Set attributeValues = new HashSet(0);

    public Article() {
    }

    public Article(Bank bank, String articleName, Set matchingsForArticleIdFrom, Set matchingsForArticleIdTo, Set attributeValues) {
        this.bank = bank;
        this.articleName = articleName;
        this.matchingsForArticleIdFrom = matchingsForArticleIdFrom;
        this.matchingsForArticleIdTo = matchingsForArticleIdTo;
        this.attributeValues = attributeValues;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    public String getArticleName() {
        return this.articleName;
    }

    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    public Set getMatchingsForArticleIdFrom() {
        return this.matchingsForArticleIdFrom;
    }

    public void setMatchingsForArticleIdFrom(Set matchingsForArticleIdFrom) {
        this.matchingsForArticleIdFrom = matchingsForArticleIdFrom;
    }

    public Set getMatchingsForArticleIdTo() {
        return this.matchingsForArticleIdTo;
    }

    public void setMatchingsForArticleIdTo(Set matchingsForArticleIdTo) {
        this.matchingsForArticleIdTo = matchingsForArticleIdTo;
    }

    public Set getAttributeValues() {
        return this.attributeValues;
    }

    public void setAttributeValues(Set attributeValues) {
        this.attributeValues = attributeValues;
    }
}


