package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AttributeType generated by hbm2java
 */
public class AttributeType  implements java.io.Serializable {


     private Integer attributeTypeId;
     private String attributeTypeName;
     private Set attributes = new HashSet(0);

    public AttributeType() {
    }

    public AttributeType(String attributeTypeName, Set attributes) {
       this.attributeTypeName = attributeTypeName;
       this.attributes = attributes;
    }
   
    public Integer getAttributeTypeId() {
        return this.attributeTypeId;
    }
    
    public void setAttributeTypeId(Integer attributeTypeId) {
        this.attributeTypeId = attributeTypeId;
    }
    public String getAttributeTypeName() {
        return this.attributeTypeName;
    }
    
    public void setAttributeTypeName(String attributeTypeName) {
        this.attributeTypeName = attributeTypeName;
    }
    public Set getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(Set attributes) {
        this.attributes = attributes;
    }




}


