package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA



/**
 * AttributeValue generated by hbm2java
 */
public class AttributeValue  implements java.io.Serializable {


     private Integer attributeValueId;
     private Attribute attribute;
     private Article article;
     private String attributeValue;

    public AttributeValue() {
    }

    public AttributeValue(Attribute attribute, Article article, String attributeValue) {
       this.attribute = attribute;
       this.article = article;
       this.attributeValue = attributeValue;
    }
   
    public Integer getAttributeValueId() {
        return this.attributeValueId;
    }
    
    public void setAttributeValueId(Integer attributeValueId) {
        this.attributeValueId = attributeValueId;
    }
    public Attribute getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }




}


