package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA



/**
 * AttributeRule generated by hbm2java
 */
public class AttributeRule  implements java.io.Serializable {


     private Integer attributeRuleId;
     private Attribute attributeByAttributeIdTo;
     private Rule rule;
     private Attribute attributeByAttributeIdFrom;
     private RuleType ruleType;
     private Unit unit;
     private Regexp regexp;

    public AttributeRule() {
    }

    public AttributeRule(Attribute attributeByAttributeIdTo, Rule rule, Attribute attributeByAttributeIdFrom, RuleType ruleType, Unit unit, Regexp regexp) {
       this.attributeByAttributeIdTo = attributeByAttributeIdTo;
       this.rule = rule;
       this.attributeByAttributeIdFrom = attributeByAttributeIdFrom;
       this.ruleType = ruleType;
       this.unit = unit;
       this.regexp = regexp;
    }
   
    public Integer getAttributeRuleId() {
        return this.attributeRuleId;
    }
    
    public void setAttributeRuleId(Integer attributeRuleId) {
        this.attributeRuleId = attributeRuleId;
    }
    public Attribute getAttributeByAttributeIdTo() {
        return this.attributeByAttributeIdTo;
    }
    
    public void setAttributeByAttributeIdTo(Attribute attributeByAttributeIdTo) {
        this.attributeByAttributeIdTo = attributeByAttributeIdTo;
    }
    public Rule getRule() {
        return this.rule;
    }
    
    public void setRule(Rule rule) {
        this.rule = rule;
    }
    public Attribute getAttributeByAttributeIdFrom() {
        return this.attributeByAttributeIdFrom;
    }
    
    public void setAttributeByAttributeIdFrom(Attribute attributeByAttributeIdFrom) {
        this.attributeByAttributeIdFrom = attributeByAttributeIdFrom;
    }
    public RuleType getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(RuleType ruleType) {
        this.ruleType = ruleType;
    }
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public Regexp getRegexp() {
        return this.regexp;
    }
    
    public void setRegexp(Regexp regexp) {
        this.regexp = regexp;
    }




}


