package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute  implements java.io.Serializable {


     private Integer attributeId;
     private Bank bank;
     private AttributeType attributeType;
     private String attributeName;
     private Set attributeToGroupes = new HashSet(0);
     private Set attributeRulesForAttributeIdTo = new HashSet(0);
     private Set attributeRulesForAttributeIdFrom = new HashSet(0);
     private Set attributeValues = new HashSet(0);

    public Attribute() {
    }

    public Attribute(Bank bank, AttributeType attributeType, String attributeName, Set attributeToGroupes, Set attributeRulesForAttributeIdTo, Set attributeRulesForAttributeIdFrom, Set attributeValues) {
       this.bank = bank;
       this.attributeType = attributeType;
       this.attributeName = attributeName;
       this.attributeToGroupes = attributeToGroupes;
       this.attributeRulesForAttributeIdTo = attributeRulesForAttributeIdTo;
       this.attributeRulesForAttributeIdFrom = attributeRulesForAttributeIdFrom;
       this.attributeValues = attributeValues;
    }
   
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public AttributeType getAttributeType() {
        return this.attributeType;
    }
    
    public void setAttributeType(AttributeType attributeType) {
        this.attributeType = attributeType;
    }
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }
    public Set getAttributeToGroupes() {
        return this.attributeToGroupes;
    }
    
    public void setAttributeToGroupes(Set attributeToGroupes) {
        this.attributeToGroupes = attributeToGroupes;
    }
    public Set getAttributeRulesForAttributeIdTo() {
        return this.attributeRulesForAttributeIdTo;
    }
    
    public void setAttributeRulesForAttributeIdTo(Set attributeRulesForAttributeIdTo) {
        this.attributeRulesForAttributeIdTo = attributeRulesForAttributeIdTo;
    }
    public Set getAttributeRulesForAttributeIdFrom() {
        return this.attributeRulesForAttributeIdFrom;
    }
    
    public void setAttributeRulesForAttributeIdFrom(Set attributeRulesForAttributeIdFrom) {
        this.attributeRulesForAttributeIdFrom = attributeRulesForAttributeIdFrom;
    }
    public Set getAttributeValues() {
        return this.attributeValues;
    }
    
    public void setAttributeValues(Set attributeValues) {
        this.attributeValues = attributeValues;
    }




}


