package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA



/**
 * GroupeToModel generated by hbm2java
 */
public class GroupeToModel  implements java.io.Serializable {


     private Integer groupeToModelId;
     private Groupe groupe;
     private Model model;

    public GroupeToModel() {
    }

    public GroupeToModel(Groupe groupe, Model model) {
       this.groupe = groupe;
       this.model = model;
    }
   
    public Integer getGroupeToModelId() {
        return this.groupeToModelId;
    }
    
    public void setGroupeToModelId(Integer groupeToModelId) {
        this.groupeToModelId = groupeToModelId;
    }
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }




}


