package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private Integer groupeId;
     private Bank bank;
     private String groupeName;
     private Set groupeToModels = new HashSet(0);
     private Set attributeToGroupes = new HashSet(0);

    public Groupe() {
    }

    public Groupe(Bank bank, String groupeName, Set groupeToModels, Set attributeToGroupes) {
       this.bank = bank;
       this.groupeName = groupeName;
       this.groupeToModels = groupeToModels;
       this.attributeToGroupes = attributeToGroupes;
    }
   
    public Integer getGroupeId() {
        return this.groupeId;
    }
    
    public void setGroupeId(Integer groupeId) {
        this.groupeId = groupeId;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public String getGroupeName() {
        return this.groupeName;
    }
    
    public void setGroupeName(String groupeName) {
        this.groupeName = groupeName;
    }
    public Set getGroupeToModels() {
        return this.groupeToModels;
    }
    
    public void setGroupeToModels(Set groupeToModels) {
        this.groupeToModels = groupeToModels;
    }
    public Set getAttributeToGroupes() {
        return this.attributeToGroupes;
    }
    
    public void setAttributeToGroupes(Set attributeToGroupes) {
        this.attributeToGroupes = attributeToGroupes;
    }




}


