package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA



/**
 * Matching generated by hbm2java
 */
public class Matching  implements java.io.Serializable {


     private Integer matchingId;
     private Bank bankByBankIdTo;
     private Article articleByArticleIdTo;
     private Article articleByArticleIdFrom;
     private Bank bankByBankIdFrom;

    public Matching() {
    }

    public Matching(Bank bankByBankIdTo, Article articleByArticleIdTo, Article articleByArticleIdFrom, Bank bankByBankIdFrom) {
       this.bankByBankIdTo = bankByBankIdTo;
       this.articleByArticleIdTo = articleByArticleIdTo;
       this.articleByArticleIdFrom = articleByArticleIdFrom;
       this.bankByBankIdFrom = bankByBankIdFrom;
    }
   
    public Integer getMatchingId() {
        return this.matchingId;
    }
    
    public void setMatchingId(Integer matchingId) {
        this.matchingId = matchingId;
    }
    public Bank getBankByBankIdTo() {
        return this.bankByBankIdTo;
    }
    
    public void setBankByBankIdTo(Bank bankByBankIdTo) {
        this.bankByBankIdTo = bankByBankIdTo;
    }
    public Article getArticleByArticleIdTo() {
        return this.articleByArticleIdTo;
    }
    
    public void setArticleByArticleIdTo(Article articleByArticleIdTo) {
        this.articleByArticleIdTo = articleByArticleIdTo;
    }
    public Article getArticleByArticleIdFrom() {
        return this.articleByArticleIdFrom;
    }
    
    public void setArticleByArticleIdFrom(Article articleByArticleIdFrom) {
        this.articleByArticleIdFrom = articleByArticleIdFrom;
    }
    public Bank getBankByBankIdFrom() {
        return this.bankByBankIdFrom;
    }
    
    public void setBankByBankIdFrom(Bank bankByBankIdFrom) {
        this.bankByBankIdFrom = bankByBankIdFrom;
    }




}


