package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private Integer modelId;
     private Bank bank;
     private String modelName;
     private Set rulesForModelIdFrom = new HashSet(0);
     private Set rulesForModelIdTo = new HashSet(0);
     private Set groupeToModels = new HashSet(0);

    public Model() {
    }

    public Model(Bank bank, String modelName, Set rulesForModelIdFrom, Set rulesForModelIdTo, Set groupeToModels) {
       this.bank = bank;
       this.modelName = modelName;
       this.rulesForModelIdFrom = rulesForModelIdFrom;
       this.rulesForModelIdTo = rulesForModelIdTo;
       this.groupeToModels = groupeToModels;
    }
   
    public Integer getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    public Set getRulesForModelIdFrom() {
        return this.rulesForModelIdFrom;
    }
    
    public void setRulesForModelIdFrom(Set rulesForModelIdFrom) {
        this.rulesForModelIdFrom = rulesForModelIdFrom;
    }
    public Set getRulesForModelIdTo() {
        return this.rulesForModelIdTo;
    }
    
    public void setRulesForModelIdTo(Set rulesForModelIdTo) {
        this.rulesForModelIdTo = rulesForModelIdTo;
    }
    public Set getGroupeToModels() {
        return this.groupeToModels;
    }
    
    public void setGroupeToModels(Set groupeToModels) {
        this.groupeToModels = groupeToModels;
    }




}


