package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RuleType generated by hbm2java
 */
public class RuleType  implements java.io.Serializable {


     private Integer ruleTypeId;
     private String ruleTypeName;
     private Set attributeRules = new HashSet(0);

    public RuleType() {
    }

    public RuleType(String ruleTypeName, Set attributeRules) {
       this.ruleTypeName = ruleTypeName;
       this.attributeRules = attributeRules;
    }
   
    public Integer getRuleTypeId() {
        return this.ruleTypeId;
    }
    
    public void setRuleTypeId(Integer ruleTypeId) {
        this.ruleTypeId = ruleTypeId;
    }
    public String getRuleTypeName() {
        return this.ruleTypeName;
    }
    
    public void setRuleTypeName(String ruleTypeName) {
        this.ruleTypeName = ruleTypeName;
    }
    public Set getAttributeRules() {
        return this.attributeRules;
    }
    
    public void setAttributeRules(Set attributeRules) {
        this.attributeRules = attributeRules;
    }




}


