package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rule generated by hbm2java
 */
public class Rule  implements java.io.Serializable {


     private Integer ruleId;
     private Model modelByModelIdTo;
     private Model modelByModelIdFrom;
     private String ruleName;
     private Set attributeRules = new HashSet(0);

    public Rule() {
    }

    public Rule(Model modelByModelIdTo, Model modelByModelIdFrom, String ruleName, Set attributeRules) {
       this.modelByModelIdTo = modelByModelIdTo;
       this.modelByModelIdFrom = modelByModelIdFrom;
       this.ruleName = ruleName;
       this.attributeRules = attributeRules;
    }
   
    public Integer getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }
    public Model getModelByModelIdTo() {
        return this.modelByModelIdTo;
    }
    
    public void setModelByModelIdTo(Model modelByModelIdTo) {
        this.modelByModelIdTo = modelByModelIdTo;
    }
    public Model getModelByModelIdFrom() {
        return this.modelByModelIdFrom;
    }
    
    public void setModelByModelIdFrom(Model modelByModelIdFrom) {
        this.modelByModelIdFrom = modelByModelIdFrom;
    }
    public String getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }
    public Set getAttributeRules() {
        return this.attributeRules;
    }
    
    public void setAttributeRules(Set attributeRules) {
        this.attributeRules = attributeRules;
    }




}


