package pojo;
// Generated 12.03.2010 15:04:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private Integer unitId;
     private String unitValue;
     private Set attributeRules = new HashSet(0);

    public Unit() {
    }

    public Unit(String unitValue, Set attributeRules) {
       this.unitValue = unitValue;
       this.attributeRules = attributeRules;
    }
   
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public String getUnitValue() {
        return this.unitValue;
    }
    
    public void setUnitValue(String unitValue) {
        this.unitValue = unitValue;
    }
    public Set getAttributeRules() {
        return this.attributeRules;
    }
    
    public void setAttributeRules(Set attributeRules) {
        this.attributeRules = attributeRules;
    }




}


