package pojo;
// Generated 29.07.2010 22:36:50 by Hibernate Tools 3.2.1.GA



/**
 * Composite generated by hbm2java
 */
public class Composite  implements java.io.Serializable {


     private Integer compositeId;
     private Attribute attribute;
     private Groupe groupe;
     private Boolean compositeValue;

    public Composite() {
    }

    public Composite(Attribute attribute, Groupe groupe, Boolean compositeValue) {
       this.attribute = attribute;
       this.groupe = groupe;
       this.compositeValue = compositeValue;
    }
   
    public Integer getCompositeId() {
        return this.compositeId;
    }
    
    public void setCompositeId(Integer compositeId) {
        this.compositeId = compositeId;
    }
    public Attribute getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    public Boolean getCompositeValue() {
        return this.compositeValue;
    }
    
    public void setCompositeValue(Boolean compositeValue) {
        this.compositeValue = compositeValue;
    }




}


