package pojo;
// Generated 29.01.2010 17:00:46 by Hibernate Tools 3.2.1.GA



/**
 * Logs generated by hbm2java
 */
public class Logs  implements java.io.Serializable {


     private Long id;
     private String ip;
     private String logType;
     private String logMessage;
     private String logTime;

    public Logs() {
    }

    public Logs(String ip, String logType, String logMessage, String logTime) {
       this.ip = ip;
       this.logType = logType;
       this.logMessage = logMessage;
       this.logTime = logTime;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getLogType() {
        return this.logType;
    }
    
    public void setLogType(String logType) {
        this.logType = logType;
    }
    public String getLogMessage() {
        return this.logMessage;
    }
    
    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }
    public String getLogTime() {
        return this.logTime;
    }
    
    public void setLogTime(String logTime) {
        this.logTime = logTime;
    }




}


