package pojo;
// Generated 02.02.2010 14:18:48 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long id;
     private String user;
     private String nick;
     private String login;
     private String password;
     private String ip;

    public Users() {
    }

	
    public Users(long id) {
        this.id = id;
    }
    public Users(long id, String user, String nick, String login, String password, String ip) {
       this.id = id;
       this.user = user;
       this.nick = nick;
       this.login = login;
       this.password = password;
       this.ip = ip;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


