package pojo;
// Generated 08.04.2010 13:05:51 by Hibernate Tools 3.2.1.GA



/**
 * ValueLanguage generated by hbm2java
 */
public class ValueLanguage  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;

    public ValueLanguage() {
    }

    public ValueLanguage(String name, String description) {
       this.name = name;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


