package Pojo;
// Generated 06.10.2009 11:06:51 by Hibernate Tools 3.2.1.GA



/**
 * CategoriesDescriptionId generated by hbm2java
 */
public class CategoriesDescriptionId  implements java.io.Serializable {


     private int categoriesId;
     private int languageId;

    public CategoriesDescriptionId() {
    }

    public CategoriesDescriptionId(int categoriesId, int languageId) {
       this.categoriesId = categoriesId;
       this.languageId = languageId;
    }
   
    public int getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(int categoriesId) {
        this.categoriesId = categoriesId;
    }
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoriesDescriptionId) ) return false;
		 CategoriesDescriptionId castOther = ( CategoriesDescriptionId ) other; 
         
		 return (this.getCategoriesId()==castOther.getCategoriesId())
 && (this.getLanguageId()==castOther.getLanguageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCategoriesId();
         result = 37 * result + this.getLanguageId();
         return result;
   }   


}


