package Pojo;
// Generated 06.10.2009 11:06:51 by Hibernate Tools 3.2.1.GA



/**
 * CategoriesArticles generated by hbm2java
 */
public class CategoriesArticles  implements java.io.Serializable {


     private int categoriesId;
     private Integer articles1Id;
     private Integer banners1Id;
     private Integer articles2Id;
     private Integer banners2Id;

    public CategoriesArticles() {
    }

	
    public CategoriesArticles(int categoriesId) {
        this.categoriesId = categoriesId;
    }
    public CategoriesArticles(int categoriesId, Integer articles1Id, Integer banners1Id, Integer articles2Id, Integer banners2Id) {
       this.categoriesId = categoriesId;
       this.articles1Id = articles1Id;
       this.banners1Id = banners1Id;
       this.articles2Id = articles2Id;
       this.banners2Id = banners2Id;
    }
   
    public int getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(int categoriesId) {
        this.categoriesId = categoriesId;
    }
    public Integer getArticles1Id() {
        return this.articles1Id;
    }
    
    public void setArticles1Id(Integer articles1Id) {
        this.articles1Id = articles1Id;
    }
    public Integer getBanners1Id() {
        return this.banners1Id;
    }
    
    public void setBanners1Id(Integer banners1Id) {
        this.banners1Id = banners1Id;
    }
    public Integer getArticles2Id() {
        return this.articles2Id;
    }
    
    public void setArticles2Id(Integer articles2Id) {
        this.articles2Id = articles2Id;
    }
    public Integer getBanners2Id() {
        return this.banners2Id;
    }
    
    public void setBanners2Id(Integer banners2Id) {
        this.banners2Id = banners2Id;
    }




}


