package Pojo;
// Generated 29.01.2010 17:00:17 by Hibernate Tools 3.2.1.GA

/**
 * ChatLogs generated by hbm2java
 */
public class ChatLogs implements java.io.Serializable {

    private Long id;
    private String ip;
    private String nick;
    private String message;

    public ChatLogs() {
    }

    public ChatLogs(String nick, String message) {
        this.nick = nick;
        this.message = message;
    }

    public ChatLogs(String ip, String nick, String message) {
        this.ip = ip;
        this.nick = nick;
        this.message = message;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getNick() {
        return this.nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}


