package Pojo;
// Generated 14.10.2009 14:15:37 by Hibernate Tools 3.2.1.GA



/**
 * PcManufacturePt generated by hbm2java
 */
public class PcManufacturePt  implements java.io.Serializable {


     private Integer idManufacturePt;
     private int idManufacture;
     private int productType;
     private int idCalc;

    public PcManufacturePt() {
    }

    public PcManufacturePt(int idManufacture, int productType, int idCalc) {
       this.idManufacture = idManufacture;
       this.productType = productType;
       this.idCalc = idCalc;
    }
   
    public Integer getIdManufacturePt() {
        return this.idManufacturePt;
    }
    
    public void setIdManufacturePt(Integer idManufacturePt) {
        this.idManufacturePt = idManufacturePt;
    }
    public int getIdManufacture() {
        return this.idManufacture;
    }
    
    public void setIdManufacture(int idManufacture) {
        this.idManufacture = idManufacture;
    }
    public int getProductType() {
        return this.productType;
    }
    
    public void setProductType(int productType) {
        this.productType = productType;
    }
    public int getIdCalc() {
        return this.idCalc;
    }
    
    public void setIdCalc(int idCalc) {
        this.idCalc = idCalc;
    }




}


