package Pojo;
// Generated 05.10.2009 11:25:48 by Hibernate Tools 3.2.1.GA



/**
 * PcProcessStatus generated by hbm2java
 */
public class PcProcessStatus  implements java.io.Serializable {


     private int processId;
     private Byte processStatus;

    public PcProcessStatus() {
    }

	
    public PcProcessStatus(int processId) {
        this.processId = processId;
    }
    public PcProcessStatus(int processId, Byte processStatus) {
       this.processId = processId;
       this.processStatus = processStatus;
    }
   
    public int getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(int processId) {
        this.processId = processId;
    }
    public Byte getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(Byte processStatus) {
        this.processStatus = processStatus;
    }




}


