package Pojo;
// Generated 09.10.2009 15:37:19 by Hibernate Tools 3.2.1.GA



/**
 * PcProductsToPt generated by hbm2java
 */
public class PcProductsToPt  implements java.io.Serializable {


     private int productsId;
     private int ptId;

    public PcProductsToPt() {
    }

    public PcProductsToPt(int productsId, int ptId) {
       this.productsId = productsId;
       this.ptId = ptId;
    }
   
    public int getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(int productsId) {
        this.productsId = productsId;
    }
    public int getPtId() {
        return this.ptId;
    }
    
    public void setPtId(int ptId) {
        this.ptId = ptId;
    }




}


