package pojo;
// Generated 01.04.2010 21:51:40 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Attribute generated by hbm2java
 */
public class Attribute implements java.io.Serializable {

    private Integer attributeId;
    private String attributeName;
    private List<Groupe> groupes = new ArrayList(0);

    public Attribute() {
    }

    public Attribute(String attributeName) {
        this.attributeName = attributeName;
    }

    public Attribute(String attributeName, List<Groupe> groupes) {
        this.attributeName = attributeName;
        this.groupes = groupes;
    }

    public Integer getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    public List<Groupe> getGroupes() {
        return this.groupes;
    }

    public void setGroupes(List<Groupe> groupes) {
        this.groupes = groupes;
    }
}


