package pojo;
// Generated 01.04.2010 21:51:40 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe implements java.io.Serializable {

    private Integer groupeId;
    private String groupeName;
    private List<ProductType> productTypes = new ArrayList(0);
    private List<Attribute> attributes = new ArrayList(0);

    public Groupe() {
    }

    public Groupe(String groupeName) {
        this.groupeName = groupeName;
    }

    public Groupe(String groupeName, List<ProductType> productTypes, List<Attribute> attributes) {
        this.groupeName = groupeName;
        this.productTypes = productTypes;
        this.attributes = attributes;
    }

    public Integer getGroupeId() {
        return this.groupeId;
    }

    public void setGroupeId(Integer groupeId) {
        this.groupeId = groupeId;
    }

    public String getGroupeName() {
        return this.groupeName;
    }

    public void setGroupeName(String groupeName) {
        this.groupeName = groupeName;
    }

    public List<ProductType> getProductTypes() {
        return this.productTypes;
    }

    public void setProductTypes(List<ProductType> productTypes) {
        this.productTypes = productTypes;
    }

    public List<Attribute> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
        this.attributes = attributes;
    }
}


