package pojo;
// Generated 01.04.2010 21:51:40 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.collection.PersistentSet;

/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

    private Integer productTypeId;
    private String productTypeName;
    private List<Groupe> groupes = new ArrayList(0);

    public ProductType() {
    }

    public ProductType(String productTypeName, List<Groupe> groupes) {
        this.productTypeName = productTypeName;
        this.groupes = groupes;
    }

    public Integer getProductTypeId() {
        return this.productTypeId;
    }

    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    public String getProductTypeName() {
        return this.productTypeName;
    }

    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public List<Groupe> getGroupes() {
        return this.groupes;
    }

    public void setGroupes(List<Groupe> groupes) {
        this.groupes = groupes;
    }
}


