package pojo;
// Generated 26.03.2010 11:08:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute  implements java.io.Serializable {


     private Integer attributeId;
     private String attributeName;
     private Set productTypes = new HashSet(0);
     private Set values = new HashSet(0);

    public Attribute() {
    }

    public Attribute(String attributeName, Set productTypes, Set values) {
       this.attributeName = attributeName;
       this.productTypes = productTypes;
       this.values = values;
    }
   
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }
    public Set getProductTypes() {
        return this.productTypes;
    }
    
    public void setProductTypes(Set productTypes) {
        this.productTypes = productTypes;
    }
    public Set getValues() {
        return this.values;
    }
    
    public void setValues(Set values) {
        this.values = values;
    }




}


