package pojo;
// Generated 29.03.2010 17:05:23 by Hibernate Tools 3.2.1.GA

/**
 * Headphones generated by hbm2java
 */
public class Headphones implements java.io.Serializable {

    private int id;
    private Integer keyArticle;
    private String fullName;
    private String picUrl;
    private String attributes;
    private String descriptions;
    private String vendor;

    public Headphones() {
    }

    public Headphones(int id) {
        this.id = id;
    }

    public Headphones(int id, Integer keyArticle, String fullName, String picUrl, String attributes, String descriptions, String vendor) {
        this.id = id;
        this.keyArticle = keyArticle;
        this.fullName = fullName;
        this.picUrl = picUrl;
        this.attributes = attributes;
        this.descriptions = descriptions;
        this.vendor = vendor;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getKeyArticle() {
        return this.keyArticle;
    }

    public void setKeyArticle(Integer keyArticle) {
        this.keyArticle = keyArticle;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    public String getDescriptions() {
        return this.descriptions;
    }

    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    public String getVendor() {
        return this.vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
}







