package pojo;
// Generated 26.03.2010 11:08:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private Integer productTypeId;
     private String productTypeName;
     private Set attributes = new HashSet(0);
     private Set values = new HashSet(0);

    public ProductType() {
    }

    public ProductType(String productTypeName, Set attributes, Set values) {
       this.productTypeName = productTypeName;
       this.attributes = attributes;
       this.values = values;
    }
   
    public Integer getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
    public String getProductTypeName() {
        return this.productTypeName;
    }
    
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }
    public Set getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(Set attributes) {
        this.attributes = attributes;
    }
    public Set getValues() {
        return this.values;
    }
    
    public void setValues(Set values) {
        this.values = values;
    }




}


