package pojo;
// Generated 17.03.2010 15:51:32 by Hibernate Tools 3.2.1.GA

/**
 * Soft generated by hbm2java
 */
public class Soft implements java.io.Serializable {

    private Integer id;
    private Integer keyArticle;
    private String fullName;
    private String picUrl;
    private String attributes;
    private String descriptions;
    private String benefits;
    private String systemRequirements;

    public Soft() {
    }

    public Soft(Integer keyArticle, String fullName, String picUrl, String attributes, String descriptions, String benefits, String systemRequirements) {
        this.keyArticle = keyArticle;
        this.fullName = fullName;
        this.picUrl = picUrl;
        this.attributes = attributes;
        this.descriptions = descriptions;
        this.benefits = benefits;
        this.systemRequirements = systemRequirements;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getKeyArticle() {
        return this.keyArticle;
    }

    public void setKeyArticle(Integer keyArticle) {
        this.keyArticle = keyArticle;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    public String getDescriptions() {
        return this.descriptions;
    }

    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    public String getBenefits() {
        return this.benefits;
    }

    public void setBenefits(String benefits) {
        this.benefits = benefits;
    }

    public String getSystemRequirements() {
        return this.systemRequirements;
    }

    public void setSystemRequirements(String systemRequirements) {
        this.systemRequirements = systemRequirements;
    }

}


