package pojo;
// Generated 26.03.2010 11:08:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Value generated by hbm2java
 */
public class Value  implements java.io.Serializable {


     private Integer valueId;
     private String valueName;
     private Set attributes = new HashSet(0);
     private Set productTypes = new HashSet(0);

    public Value() {
    }

    public Value(String valueName, Set attributes, Set productTypes) {
       this.valueName = valueName;
       this.attributes = attributes;
       this.productTypes = productTypes;
    }
   
    public Integer getValueId() {
        return this.valueId;
    }
    
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }
    public String getValueName() {
        return this.valueName;
    }
    
    public void setValueName(String valueName) {
        this.valueName = valueName;
    }
    public Set getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(Set attributes) {
        this.attributes = attributes;
    }
    public Set getProductTypes() {
        return this.productTypes;
    }
    
    public void setProductTypes(Set productTypes) {
        this.productTypes = productTypes;
    }




}


