package Yandex;
// Generated 23.08.2009 19:03:49 by Hibernate Tools 3.2.1.GA


import java.sql.Date;

/**
 * Yandexprices generated by hbm2java
 */
public class Yandexprices  implements java.io.Serializable {


     private int id;
     private String productName;
     private String concurent;
     private String delivery;
     private String opinion;
     private Double price;
     private String url;
     private Date data;

    public Yandexprices() {
    }

	
    public Yandexprices(int id, Date data) {
        this.id = id;
        this.data = data;
    }
    public Yandexprices(int id, String productName, String concurent, String delivery, String opinion, Double price, String url, Date data) {
       this.id = id;
       this.productName = productName;
       this.concurent = concurent;
       this.delivery = delivery;
       this.opinion = opinion;
       this.price = price;
       this.url = url;
       this.data = data;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getConcurent() {
        return this.concurent;
    }
    
    public void setConcurent(String concurent) {
        this.concurent = concurent;
    }
    public String getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(String delivery) {
        this.delivery = delivery;
    }
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


