package pojo;
// Generated 06.01.2010 13:28:43 by Hibernate Tools 3.2.1.GA



/**
 * Articles generated by hbm2java
 */
public class Articles  implements java.io.Serializable {


     private long articleId;
     private String article;

    public Articles() {
    }

	
    public Articles(long articleId) {
        this.articleId = articleId;
    }
    public Articles(long articleId, String article) {
       this.articleId = articleId;
       this.article = article;
    }
   
    public long getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(long articleId) {
        this.articleId = articleId;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }




}


