package pojo;
// Generated 06.10.2009 11:06:51 by Hibernate Tools 3.2.1.GA



/**
 * CategoriesDescription generated by hbm2java
 */
public class CategoriesDescription  implements java.io.Serializable {


     private CategoriesDescriptionId id;
     private String categoriesName;
     private String categoriesHeadingTitle;
     private String categoriesDescription;
     private String categoriesMetaTitle;
     private String categoriesMetaDescription;
     private String categoriesMetaKeywords;

    public CategoriesDescription() {
    }

	
    public CategoriesDescription(CategoriesDescriptionId id, String categoriesName) {
        this.id = id;
        this.categoriesName = categoriesName;
    }
    public CategoriesDescription(CategoriesDescriptionId id, String categoriesName, String categoriesHeadingTitle, String categoriesDescription, String categoriesMetaTitle, String categoriesMetaDescription, String categoriesMetaKeywords) {
       this.id = id;
       this.categoriesName = categoriesName;
       this.categoriesHeadingTitle = categoriesHeadingTitle;
       this.categoriesDescription = categoriesDescription;
       this.categoriesMetaTitle = categoriesMetaTitle;
       this.categoriesMetaDescription = categoriesMetaDescription;
       this.categoriesMetaKeywords = categoriesMetaKeywords;
    }
   
    public CategoriesDescriptionId getId() {
        return this.id;
    }
    
    public void setId(CategoriesDescriptionId id) {
        this.id = id;
    }
    public String getCategoriesName() {
        return this.categoriesName;
    }
    
    public void setCategoriesName(String categoriesName) {
        this.categoriesName = categoriesName;
    }
    public String getCategoriesHeadingTitle() {
        return this.categoriesHeadingTitle;
    }
    
    public void setCategoriesHeadingTitle(String categoriesHeadingTitle) {
        this.categoriesHeadingTitle = categoriesHeadingTitle;
    }
    public String getCategoriesDescription() {
        return this.categoriesDescription;
    }
    
    public void setCategoriesDescription(String categoriesDescription) {
        this.categoriesDescription = categoriesDescription;
    }
    public String getCategoriesMetaTitle() {
        return this.categoriesMetaTitle;
    }
    
    public void setCategoriesMetaTitle(String categoriesMetaTitle) {
        this.categoriesMetaTitle = categoriesMetaTitle;
    }
    public String getCategoriesMetaDescription() {
        return this.categoriesMetaDescription;
    }
    
    public void setCategoriesMetaDescription(String categoriesMetaDescription) {
        this.categoriesMetaDescription = categoriesMetaDescription;
    }
    public String getCategoriesMetaKeywords() {
        return this.categoriesMetaKeywords;
    }
    
    public void setCategoriesMetaKeywords(String categoriesMetaKeywords) {
        this.categoriesMetaKeywords = categoriesMetaKeywords;
    }




}


