package pojo;
// Generated 14.07.2010 22:31:46 by Hibernate Tools 3.2.1.GA

/**
 * InputData generated by hbm2java
 */
public class InputData implements java.io.Serializable {

    private Integer id;
    private long sessionId;
    private String fullName;
    private String manufacturer;
    private String article;
    private String productType;
    private String picUrl;
    private String groupe;
    private String attribute;
    private String attributeValue;

    public InputData() {
    }

    public InputData(int sessionId) {
        this.sessionId = sessionId;
    }

    public InputData(int sessionId, String fullName, String manufacturer, String article, String productType, String picUrl, String groupe, String attribute, String attributeValue) {
        this.sessionId = sessionId;
        this.fullName = fullName;
        this.manufacturer = manufacturer;
        this.article = article;
        this.productType = productType;
        this.picUrl = picUrl;
        this.groupe = groupe;
        this.attribute = attribute;
        this.attributeValue = attributeValue;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public long getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getArticle() {
        return this.article;
    }

    public void setArticle(String article) {
        this.article = article;
    }

    public String getProductType() {
        return this.productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getGroupe() {
        return this.groupe;
    }

    public void setGroupe(String groupe) {
        this.groupe = groupe;
    }

    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public String getAttributeValue() {
        return this.attributeValue;
    }

    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
}
