package pojo;
// Generated 14.10.2009 15:47:44 by Hibernate Tools 3.2.1.GA



/**
 * ManufacturersInfoId generated by hbm2java
 */
public class ManufacturersInfoId  implements java.io.Serializable {


     private int manufacturersId;
     private int languagesId;

    public ManufacturersInfoId() {
    }

    public ManufacturersInfoId(int manufacturersId, int languagesId) {
       this.manufacturersId = manufacturersId;
       this.languagesId = languagesId;
    }
   
    public int getManufacturersId() {
        return this.manufacturersId;
    }
    
    public void setManufacturersId(int manufacturersId) {
        this.manufacturersId = manufacturersId;
    }
    public int getLanguagesId() {
        return this.languagesId;
    }
    
    public void setLanguagesId(int languagesId) {
        this.languagesId = languagesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ManufacturersInfoId) ) return false;
		 ManufacturersInfoId castOther = ( ManufacturersInfoId ) other; 
         
		 return (this.getManufacturersId()==castOther.getManufacturersId())
 && (this.getLanguagesId()==castOther.getLanguagesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getManufacturersId();
         result = 37 * result + this.getLanguagesId();
         return result;
   }   


}


