package pojo;
// Generated 14.10.2009 15:47:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Manufacturers generated by hbm2java
 */
public class Manufacturers  implements java.io.Serializable {


     private Integer manufacturersId;
     private String manufacturersImage;
     private Date dateAdded;
     private Date lastModified;

    public Manufacturers() {
    }

    public Manufacturers(String manufacturersImage, Date dateAdded, Date lastModified) {
       this.manufacturersImage = manufacturersImage;
       this.dateAdded = dateAdded;
       this.lastModified = lastModified;
    }
   
    public Integer getManufacturersId() {
        return this.manufacturersId;
    }
    
    public void setManufacturersId(Integer manufacturersId) {
        this.manufacturersId = manufacturersId;
    }
    public String getManufacturersImage() {
        return this.manufacturersImage;
    }
    
    public void setManufacturersImage(String manufacturersImage) {
        this.manufacturersImage = manufacturersImage;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


