package pojo;
// Generated 13.05.2010 10:09:46 by Hibernate Tools 3.2.1.GA

/**
 * OutputData generated by hbm2java
 */
public class OutputData implements java.io.Serializable {

    private Integer outputDataId;
    private Long sessionId;
    private String article;
    private String productType;
    private String groupe;
    private String attribute;
    private String value;
    private String unit;
    private Byte available;

    public OutputData() {
    }

    public OutputData(Long sessionId, String article, String productType, String groupe, String attribute, String value, String unit, Byte available) {
        this.sessionId = sessionId;
        this.article = article;
        this.productType = productType;
        this.groupe = groupe;
        this.attribute = attribute;
        this.value = value;
        this.unit = unit;
        this.available = available;
    }

    public Integer getOutputDataId() {
        return this.outputDataId;
    }

    public void setOutputDataId(Integer outputDataId) {
        this.outputDataId = outputDataId;
    }

    public Long getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    public String getArticle() {
        return this.article;
    }

    public void setArticle(String article) {
        this.article = article;
    }

    public String getGroupe() {
        return this.groupe;
    }

    public void setGroupe(String groupe) {
        this.groupe = groupe;
    }

    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Byte getAvailable() {
        return this.available;
    }

    public void setAvailable(Byte available) {
        this.available = available;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }
}


