package pojo;
// Generated 05.10.2009 11:25:48 by Hibernate Tools 3.2.1.GA



/**
 * PcSyncProductsToCategoriesId generated by hbm2java
 */
public class PcSyncProductsToCategoriesId  implements java.io.Serializable {


     private int productsId;
     private int categoriesId;

    public PcSyncProductsToCategoriesId() {
    }

    public PcSyncProductsToCategoriesId(int productsId, int categoriesId) {
       this.productsId = productsId;
       this.categoriesId = categoriesId;
    }
   
    public int getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(int productsId) {
        this.productsId = productsId;
    }
    public int getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(int categoriesId) {
        this.categoriesId = categoriesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PcSyncProductsToCategoriesId) ) return false;
		 PcSyncProductsToCategoriesId castOther = ( PcSyncProductsToCategoriesId ) other; 
         
		 return (this.getProductsId()==castOther.getProductsId())
 && (this.getCategoriesId()==castOther.getCategoriesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductsId();
         result = 37 * result + this.getCategoriesId();
         return result;
   }   


}


