package pojo;
// Generated 10.11.2009 16:32:15 by Hibernate Tools 3.2.1.GA



/**
 * PcSyncIds generated by hbm2java
 */
public class PcSyncIds  implements java.io.Serializable {


     private long it4pid;
     private long shoppid;

    public PcSyncIds() {
    }

    public PcSyncIds(long it4pid, long shoppid) {
       this.it4pid = it4pid;
       this.shoppid = shoppid;
    }
   
    public long getIt4pid() {
        return this.it4pid;
    }
    
    public void setIt4pid(long it4pid) {
        this.it4pid = it4pid;
    }
    public long getShoppid() {
        return this.shoppid;
    }
    
    public void setShoppid(long shoppid) {
        this.shoppid = shoppid;
    }




}


