package pojo;
// Generated 07.10.2009 12:54:40 by Hibernate Tools 3.2.1.GA



/**
 * ProductsToCategories generated by hbm2java
 */
public class ProductsToCategories  implements java.io.Serializable {


     private ProductsToCategoriesId id;

    public ProductsToCategories() {
    }

    public ProductsToCategories(ProductsToCategoriesId id) {
       this.id = id;
    }
   
    public ProductsToCategoriesId getId() {
        return this.id;
    }
    
    public void setId(ProductsToCategoriesId id) {
        this.id = id;
    }




}


