package pojo;
// Generated 26.10.2009 10:07:36 by Hibernate Tools 3.2.1.GA

/**
 * ProductsImages generated by hbm2java
 */
public class ProductsImages implements java.io.Serializable {

    private Integer id;
    private int productId;
    private String imgXs;
    private String imgS;
    private String imgM;
    private String imgB;
    private int ordered;

    public ProductsImages() {
    }

    public ProductsImages(int productId, String imgXs, String imgS, String imgM, String imgB, int ordered) {
        this.productId = productId;
        this.imgXs = imgXs;
        this.imgS = imgS;
        this.imgM = imgM;
        this.imgB = imgB;
        this.ordered = ordered;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public String getImgXs() {
        return this.imgXs;
    }

    public void setImgXs(String imgXs) {
        this.imgXs = imgXs;
    }

    public String getImgS() {
        return this.imgS;
    }

    public void setImgS(String imgS) {
        this.imgS = imgS;
    }

    public String getImgM() {
        return this.imgM;
    }

    public void setImgM(String imgM) {
        this.imgM = imgM;
    }

    public String getImgB() {
        return this.imgB;
    }

    public void setImgB(String imgB) {
        this.imgB = imgB;
    }

    public int getOrdered() {
        return this.ordered;
    }

    public void setOrdered(int ordered) {
        this.ordered = ordered;
    }
}


