package pojo;
// Generated 05.04.2010 14:56:34 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
  
/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

    private Integer productTypeId;
    private String productTypeName;
    private String productTypeAlternative;
    private List<Attribute> attributes = new ArrayList(0);

    public ProductType() {
    }

    public ProductType(String productTypeName, String productTypeAlternative, List<Attribute> attributes) {
        this.productTypeName = productTypeName;
        this.productTypeAlternative = productTypeAlternative;
        this.attributes = attributes;
    }

    public ProductType(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public Integer getProductTypeId() {
        return this.productTypeId;
    }

    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    public String getProductTypeName() {
        return this.productTypeName;
    }

    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public String getProductTypeAlternative() {
        return this.productTypeAlternative;
    }

    public void setProductTypeAlternative(String productTypeAlternative) {
        this.productTypeAlternative = productTypeAlternative;
    }

    public List<Attribute> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
        this.attributes = attributes;
    }
}


