package pojo;
// Generated 13.07.2010 16:05:17 by Hibernate Tools 3.2.1.GA

/**
 * Regexp generated by hbm2java
 */
public class Regexp implements java.io.Serializable {

    private Integer regexpId;
    private Attribute attribute;
    private String regexpType;
    private String regexpPattern;
    private String regexpReplacement;
    private Integer groupeId;

    public Regexp() {
    }

    public Regexp(Attribute attribute) {
        this.attribute = attribute;
    }

    public Regexp(Attribute attribute, String regexpType, String regexpPattern, String regexpReplacement) {
        this.attribute = attribute;
        this.regexpType = regexpType;
        this.regexpPattern = regexpPattern;
        this.regexpReplacement = regexpReplacement;
    }

    public Integer getRegexpId() {
        return this.regexpId;
    }

    public void setRegexpId(Integer regexpId) {
        this.regexpId = regexpId;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public String getRegexpType() {
        return this.regexpType;
    }

    public void setRegexpType(String regexpType) {
        this.regexpType = regexpType;
    }

    public String getRegexpPattern() {
        return this.regexpPattern;
    }

    public void setRegexpPattern(String regexpPattern) {
        this.regexpPattern = regexpPattern;
    }

    public String getRegexpReplacement() {
        return this.regexpReplacement;
    }

    public void setRegexpReplacement(String regexpReplacement) {
        this.regexpReplacement = regexpReplacement;
    }

    public Integer getGroupeId() {
        return groupeId;
    }

    public void setGroupeId(Integer groupeId) {
        this.groupeId = groupeId;
    }
}
