package pojo;
// Generated 16.06.2010 23:40:34 by Hibernate Tools 3.2.1.GA



/**
 * UnitAlternativeName generated by hbm2java
 */
public class UnitAlternativeName  implements java.io.Serializable {


     private Integer unitAlernativeNameId;
     private Unit unit;
     private String unitAlernativeNameValue;

    public UnitAlternativeName() {
    }

	
    public UnitAlternativeName(Unit unit) {
        this.unit = unit;
    }
    public UnitAlternativeName(Unit unit, String unitAlernativeNameValue) {
       this.unit = unit;
       this.unitAlernativeNameValue = unitAlernativeNameValue;
    }
   
    public Integer getUnitAlernativeNameId() {
        return this.unitAlernativeNameId;
    }
    
    public void setUnitAlernativeNameId(Integer unitAlernativeNameId) {
        this.unitAlernativeNameId = unitAlernativeNameId;
    }
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public String getUnitAlernativeNameValue() {
        return this.unitAlernativeNameValue;
    }
    
    public void setUnitAlernativeNameValue(String unitAlernativeNameValue) {
        this.unitAlernativeNameValue = unitAlernativeNameValue;
    }




}


