package Pojo;
// Generated 07.11.2009 18:22:22 by Hibernate Tools 3.2.1.GA



/**
 * Articles generated by hbm2java
 */
public class Articles  implements java.io.Serializable {


     private Long id;
     private String article;
     private String description;
     private Double price;

    public Articles() {
    }

    public Articles(String article, String description, Double price) {
       this.article = article;
       this.description = description;
       this.price = price;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


