package Pojo;
// Generated 16.12.2009 11:27:33 by Hibernate Tools 3.2.1.GA

/**
 * It4articles generated by hbm2java
 */
public class It4articles implements java.io.Serializable {

    private Long id;
    private String it4article;
    private String description;
    private String keyarticle;
    private Byte type;

    public It4articles() {
    }

    public It4articles(String it4article, String description, String keyarticle, Byte type) {
        this.it4article = it4article;
        this.description = description;
        this.keyarticle = keyarticle;
        this.type = type;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIt4article() {
        return this.it4article;
    }

    public void setIt4article(String it4article) {
        this.it4article = it4article;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getKeyarticle() {
        return this.keyarticle;
    }

    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }

    public Byte getType() {
        return this.type;
    }

    public void setType(Byte type) {
        this.type = type;
    }
}


