package Pojo;
// Generated 15.12.2009 13:00:51 by Hibernate Tools 3.2.1.GA



/**
 * It4articles generated by hbm2java
 */
public class It4articles  implements java.io.Serializable {


     private long id;
     private String it4article;

    public It4articles() {
    }

	
    public It4articles(long id) {
        this.id = id;
    }
    public It4articles(long id, String it4article) {
       this.id = id;
       this.it4article = it4article;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getIt4article() {
        return this.it4article;
    }
    
    public void setIt4article(String it4article) {
        this.it4article = it4article;
    }




}


