package Pojo;
// Generated 23.04.2010 16:42:04 by Hibernate Tools 3.2.1.GA



/**
 * KeyFromXml generated by hbm2java
 */
public class KeyFromXml  implements java.io.Serializable {


     private long id;
     private String keyart;
     private String vendor;
     private String pt;
     private String picurl;
     private String attr;
     private String fullname;

    public KeyFromXml() {
    }

	
    public KeyFromXml(long id) {
        this.id = id;
    }
    public KeyFromXml(long id, String keyart, String vendor, String pt, String picurl, String attr, String fullname) {
       this.id = id;
       this.keyart = keyart;
       this.vendor = vendor;
       this.pt = pt;
       this.picurl = picurl;
       this.attr = attr;
       this.fullname = fullname;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getKeyart() {
        return this.keyart;
    }
    
    public void setKeyart(String keyart) {
        this.keyart = keyart;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getPt() {
        return this.pt;
    }
    
    public void setPt(String pt) {
        this.pt = pt;
    }
    public String getPicurl() {
        return this.picurl;
    }
    
    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }
    public String getAttr() {
        return this.attr;
    }
    
    public void setAttr(String attr) {
        this.attr = attr;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }




}


