package Pojo;
// Generated 27.04.2010 12:21:14 by Hibernate Tools 3.2.1.GA



/**
 * MarkFromXml generated by hbm2java
 */
public class MarkFromXml  implements java.io.Serializable {


     private Long id;
     private String keyart;
     private String marketing;

    public MarkFromXml() {
    }

    public MarkFromXml(String keyart, String marketing) {
       this.keyart = keyart;
       this.marketing = marketing;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getKeyart() {
        return this.keyart;
    }
    
    public void setKeyart(String keyart) {
        this.keyart = keyart;
    }
    public String getMarketing() {
        return this.marketing;
    }
    
    public void setMarketing(String marketing) {
        this.marketing = marketing;
    }




}


