package Pojo;
// Generated 18.12.2009 12:53:15 by Hibernate Tools 3.2.1.GA



/**
 * Matching generated by hbm2java
 */
public class Matching  implements java.io.Serializable {


     private Long id;
     private String keyarticle;
     private String keydesc;
     private String apparticle;
     private String yadata;

    public Matching() {
    }

    public Matching(String keyarticle, String keydesc, String apparticle, String yadata) {
       this.keyarticle = keyarticle;
       this.keydesc = keydesc;
       this.apparticle = apparticle;
       this.yadata = yadata;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getKeyarticle() {
        return this.keyarticle;
    }
    
    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }
    public String getKeydesc() {
        return this.keydesc;
    }
    
    public void setKeydesc(String keydesc) {
        this.keydesc = keydesc;
    }
    public String getApparticle() {
        return this.apparticle;
    }
    
    public void setApparticle(String apparticle) {
        this.apparticle = apparticle;
    }
    public String getYadata() {
        return this.yadata;
    }
    
    public void setYadata(String yadata) {
        this.yadata = yadata;
    }




}


