package Pojo;
// Generated 07.11.2009 18:22:22 by Hibernate Tools 3.2.1.GA

/**
 * RivalsdataId generated by hbm2java
 */
public class RivalsdataId implements java.io.Serializable {

    private long rivalId;
    private long articleId;

    public RivalsdataId() {
    }

    public RivalsdataId(long rivalId, long articleId) {
        this.rivalId = rivalId;
        this.articleId = articleId;
    }

    public long getRivalId() {
        return this.rivalId;
    }

    public void setRivalId(long rivalId) {
        this.rivalId = rivalId;
    }

    public long getArticleId() {
        return this.articleId;
    }

    public void setArticleId(long articleId) {
        this.articleId = articleId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RivalsdataId)) {
            return false;
        }
        RivalsdataId castOther = (RivalsdataId) other;

        return (this.getRivalId() == castOther.getRivalId()) && (this.getArticleId() == castOther.getArticleId());
    }

    @Override
    public String toString() {
        return "Id Поставщика -> " + this.getRivalId() + " Id Артикля -> " + this.getArticleId();
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getRivalId();
        result = 37 * result + (int) this.getArticleId();
        return result;
    }
}


