package Pojo;
// Generated 05.10.2009 11:25:48 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * PcSyncProducts generated by hbm2java
 */
public class PcSyncProducts implements java.io.Serializable {

    private Long productsId;
    private int productsQuantity;
    private String productsModel;
    private BigDecimal productsPrice;
    private String manufacturersName;
    private Integer manufacturersId;

    public PcSyncProducts() {
    }

    public PcSyncProducts(int productsQuantity, BigDecimal productsPrice) {
        this.productsQuantity = productsQuantity;
        this.productsPrice = productsPrice;
    }

    public PcSyncProducts(int productsQuantity, String productsModel, BigDecimal productsPrice, String manufacturersName, Integer manufacturersId) {
        this.productsQuantity = productsQuantity;
        this.productsModel = productsModel;
        this.productsPrice = productsPrice;
        this.manufacturersName = manufacturersName;
        this.manufacturersId = manufacturersId;
    }

    public Long getProductsId() {
        return this.productsId;
    }

    public void setProductsId(Long productsId) {
        this.productsId = productsId;
    }

    public int getProductsQuantity() {
        return this.productsQuantity;
    }

    public void setProductsQuantity(int productsQuantity) {
        this.productsQuantity = productsQuantity;
    }

    public String getProductsModel() {
        return this.productsModel;
    }

    public void setProductsModel(String productsModel) {
        this.productsModel = productsModel;
    }

    public BigDecimal getProductsPrice() {
        return this.productsPrice;
    }

    public void setProductsPrice(BigDecimal productsPrice) {
        this.productsPrice = productsPrice;
    }

    public String getManufacturersName() {
        return this.manufacturersName;
    }

    public void setManufacturersName(String manufacturersName) {
        this.manufacturersName = manufacturersName;
    }

    public Integer getManufacturersId() {
        return this.manufacturersId;
    }

    public void setManufacturersId(Integer manufacturersId) {
        this.manufacturersId = manufacturersId;
    }
}


