package Pojo;
// Generated 05.10.2009 11:25:48 by Hibernate Tools 3.2.1.GA



/**
 * PcSyncProductsToCategories generated by hbm2java
 */
public class PcSyncProductsToCategories  implements java.io.Serializable {


     private PcSyncProductsToCategoriesId id;

    public PcSyncProductsToCategories() {
    }

    public PcSyncProductsToCategories(PcSyncProductsToCategoriesId id) {
       this.id = id;
    }
   
    public PcSyncProductsToCategoriesId getId() {
        return this.id;
    }
    
    public void setId(PcSyncProductsToCategoriesId id) {
        this.id = id;
    }




}


