package Pojo;
// Generated 08.10.2009 12:04:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Long productsId;
     private int productsQuantity;
     private String productsModel;
     private String productsImage;
     private String productsImageMed;
     private String productsImageLrg;
     private String productsImageSm1;
     private String productsImageXl1;
     private String productsImageSm2;
     private String productsImageXl2;
     private String productsImageSm3;
     private String productsImageXl3;
     private String productsImageSm4;
     private String productsImageXl4;
     private String productsImageSm5;
     private String productsImageXl5;
     private String productsImageSm6;
     private String productsImageXl6;
     private BigDecimal productsPrice;
     private Date productsDateAdded;
     private Date productsLastModified;
     private Date productsDateAvailable;
     private BigDecimal productsWeight;
     private boolean productsStatus;
     private boolean productsToXml;
     private int productsTaxClassId;
     private Integer manufacturersId;
     private int productsOrdered;
     private int productsQuantityOrderMin;
     private int productsQuantityOrderUnits;
     private int productsSortOrder;
     private int productsIsSync;
     private String productsYmName;
     private String productsBundle;
     private int productsDfg;
     private int productsIsExt;
     private int altDescriptionStatus;
     private boolean productAvailable;
     private String productsLogotype;
     private boolean productsHot;
     private Boolean productsDefend;
     private Integer productsKit;

    public Products() {
    }

	
    public Products(int productsQuantity, Date productsDateAdded, BigDecimal productsWeight, boolean productsStatus, boolean productsToXml, int productsTaxClassId, int productsOrdered, int productsQuantityOrderMin, int productsQuantityOrderUnits, int productsSortOrder, int productsIsSync, String productsYmName, int productsDfg, int productsIsExt, int altDescriptionStatus, boolean productAvailable, boolean productsHot) {
        this.productsQuantity = productsQuantity;
        this.productsDateAdded = productsDateAdded;
        this.productsWeight = productsWeight;
        this.productsStatus = productsStatus;
        this.productsToXml = productsToXml;
        this.productsTaxClassId = productsTaxClassId;
        this.productsOrdered = productsOrdered;
        this.productsQuantityOrderMin = productsQuantityOrderMin;
        this.productsQuantityOrderUnits = productsQuantityOrderUnits;
        this.productsSortOrder = productsSortOrder;
        this.productsIsSync = productsIsSync;
        this.productsYmName = productsYmName;
        this.productsDfg = productsDfg;
        this.productsIsExt = productsIsExt;
        this.altDescriptionStatus = altDescriptionStatus;
        this.productAvailable = productAvailable;
        this.productsHot = productsHot;
    }
    public Products(int productsQuantity, String productsModel, String productsImage, String productsImageMed, String productsImageLrg, String productsImageSm1, String productsImageXl1, String productsImageSm2, String productsImageXl2, String productsImageSm3, String productsImageXl3, String productsImageSm4, String productsImageXl4, String productsImageSm5, String productsImageXl5, String productsImageSm6, String productsImageXl6, BigDecimal productsPrice, Date productsDateAdded, Date productsLastModified, Date productsDateAvailable, BigDecimal productsWeight, boolean productsStatus, boolean productsToXml, int productsTaxClassId, Integer manufacturersId, int productsOrdered, int productsQuantityOrderMin, int productsQuantityOrderUnits, int productsSortOrder, int productsIsSync, String productsYmName, String productsBundle, int productsDfg, int productsIsExt, int altDescriptionStatus, boolean productAvailable, String productsLogotype, boolean productsHot, Boolean productsDefend, Integer productsKit) {
       this.productsQuantity = productsQuantity;
       this.productsModel = productsModel;
       this.productsImage = productsImage;
       this.productsImageMed = productsImageMed;
       this.productsImageLrg = productsImageLrg;
       this.productsImageSm1 = productsImageSm1;
       this.productsImageXl1 = productsImageXl1;
       this.productsImageSm2 = productsImageSm2;
       this.productsImageXl2 = productsImageXl2;
       this.productsImageSm3 = productsImageSm3;
       this.productsImageXl3 = productsImageXl3;
       this.productsImageSm4 = productsImageSm4;
       this.productsImageXl4 = productsImageXl4;
       this.productsImageSm5 = productsImageSm5;
       this.productsImageXl5 = productsImageXl5;
       this.productsImageSm6 = productsImageSm6;
       this.productsImageXl6 = productsImageXl6;
       this.productsPrice = productsPrice;
       this.productsDateAdded = productsDateAdded;
       this.productsLastModified = productsLastModified;
       this.productsDateAvailable = productsDateAvailable;
       this.productsWeight = productsWeight;
       this.productsStatus = productsStatus;
       this.productsToXml = productsToXml;
       this.productsTaxClassId = productsTaxClassId;
       this.manufacturersId = manufacturersId;
       this.productsOrdered = productsOrdered;
       this.productsQuantityOrderMin = productsQuantityOrderMin;
       this.productsQuantityOrderUnits = productsQuantityOrderUnits;
       this.productsSortOrder = productsSortOrder;
       this.productsIsSync = productsIsSync;
       this.productsYmName = productsYmName;
       this.productsBundle = productsBundle;
       this.productsDfg = productsDfg;
       this.productsIsExt = productsIsExt;
       this.altDescriptionStatus = altDescriptionStatus;
       this.productAvailable = productAvailable;
       this.productsLogotype = productsLogotype;
       this.productsHot = productsHot;
       this.productsDefend = productsDefend;
       this.productsKit = productsKit;
    }
   
    public Long getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(Long productsId) {
        this.productsId = productsId;
    }
    public int getProductsQuantity() {
        return this.productsQuantity;
    }
    
    public void setProductsQuantity(int productsQuantity) {
        this.productsQuantity = productsQuantity;
    }
    public String getProductsModel() {
        return this.productsModel;
    }
    
    public void setProductsModel(String productsModel) {
        this.productsModel = productsModel;
    }
    public String getProductsImage() {
        return this.productsImage;
    }
    
    public void setProductsImage(String productsImage) {
        this.productsImage = productsImage;
    }
    public String getProductsImageMed() {
        return this.productsImageMed;
    }
    
    public void setProductsImageMed(String productsImageMed) {
        this.productsImageMed = productsImageMed;
    }
    public String getProductsImageLrg() {
        return this.productsImageLrg;
    }
    
    public void setProductsImageLrg(String productsImageLrg) {
        this.productsImageLrg = productsImageLrg;
    }
    public String getProductsImageSm1() {
        return this.productsImageSm1;
    }
    
    public void setProductsImageSm1(String productsImageSm1) {
        this.productsImageSm1 = productsImageSm1;
    }
    public String getProductsImageXl1() {
        return this.productsImageXl1;
    }
    
    public void setProductsImageXl1(String productsImageXl1) {
        this.productsImageXl1 = productsImageXl1;
    }
    public String getProductsImageSm2() {
        return this.productsImageSm2;
    }
    
    public void setProductsImageSm2(String productsImageSm2) {
        this.productsImageSm2 = productsImageSm2;
    }
    public String getProductsImageXl2() {
        return this.productsImageXl2;
    }
    
    public void setProductsImageXl2(String productsImageXl2) {
        this.productsImageXl2 = productsImageXl2;
    }
    public String getProductsImageSm3() {
        return this.productsImageSm3;
    }
    
    public void setProductsImageSm3(String productsImageSm3) {
        this.productsImageSm3 = productsImageSm3;
    }
    public String getProductsImageXl3() {
        return this.productsImageXl3;
    }
    
    public void setProductsImageXl3(String productsImageXl3) {
        this.productsImageXl3 = productsImageXl3;
    }
    public String getProductsImageSm4() {
        return this.productsImageSm4;
    }
    
    public void setProductsImageSm4(String productsImageSm4) {
        this.productsImageSm4 = productsImageSm4;
    }
    public String getProductsImageXl4() {
        return this.productsImageXl4;
    }
    
    public void setProductsImageXl4(String productsImageXl4) {
        this.productsImageXl4 = productsImageXl4;
    }
    public String getProductsImageSm5() {
        return this.productsImageSm5;
    }
    
    public void setProductsImageSm5(String productsImageSm5) {
        this.productsImageSm5 = productsImageSm5;
    }
    public String getProductsImageXl5() {
        return this.productsImageXl5;
    }
    
    public void setProductsImageXl5(String productsImageXl5) {
        this.productsImageXl5 = productsImageXl5;
    }
    public String getProductsImageSm6() {
        return this.productsImageSm6;
    }
    
    public void setProductsImageSm6(String productsImageSm6) {
        this.productsImageSm6 = productsImageSm6;
    }
    public String getProductsImageXl6() {
        return this.productsImageXl6;
    }
    
    public void setProductsImageXl6(String productsImageXl6) {
        this.productsImageXl6 = productsImageXl6;
    }
    public BigDecimal getProductsPrice() {
        return this.productsPrice;
    }
    
    public void setProductsPrice(BigDecimal productsPrice) {
        this.productsPrice = productsPrice;
    }
    public Date getProductsDateAdded() {
        return this.productsDateAdded;
    }
    
    public void setProductsDateAdded(Date productsDateAdded) {
        this.productsDateAdded = productsDateAdded;
    }
    public Date getProductsLastModified() {
        return this.productsLastModified;
    }
    
    public void setProductsLastModified(Date productsLastModified) {
        this.productsLastModified = productsLastModified;
    }
    public Date getProductsDateAvailable() {
        return this.productsDateAvailable;
    }
    
    public void setProductsDateAvailable(Date productsDateAvailable) {
        this.productsDateAvailable = productsDateAvailable;
    }
    public BigDecimal getProductsWeight() {
        return this.productsWeight;
    }
    
    public void setProductsWeight(BigDecimal productsWeight) {
        this.productsWeight = productsWeight;
    }
    public boolean isProductsStatus() {
        return this.productsStatus;
    }
    
    public void setProductsStatus(boolean productsStatus) {
        this.productsStatus = productsStatus;
    }
    public boolean isProductsToXml() {
        return this.productsToXml;
    }
    
    public void setProductsToXml(boolean productsToXml) {
        this.productsToXml = productsToXml;
    }
    public int getProductsTaxClassId() {
        return this.productsTaxClassId;
    }
    
    public void setProductsTaxClassId(int productsTaxClassId) {
        this.productsTaxClassId = productsTaxClassId;
    }
    public Integer getManufacturersId() {
        return this.manufacturersId;
    }
    
    public void setManufacturersId(Integer manufacturersId) {
        this.manufacturersId = manufacturersId;
    }
    public int getProductsOrdered() {
        return this.productsOrdered;
    }
    
    public void setProductsOrdered(int productsOrdered) {
        this.productsOrdered = productsOrdered;
    }
    public int getProductsQuantityOrderMin() {
        return this.productsQuantityOrderMin;
    }
    
    public void setProductsQuantityOrderMin(int productsQuantityOrderMin) {
        this.productsQuantityOrderMin = productsQuantityOrderMin;
    }
    public int getProductsQuantityOrderUnits() {
        return this.productsQuantityOrderUnits;
    }
    
    public void setProductsQuantityOrderUnits(int productsQuantityOrderUnits) {
        this.productsQuantityOrderUnits = productsQuantityOrderUnits;
    }
    public int getProductsSortOrder() {
        return this.productsSortOrder;
    }
    
    public void setProductsSortOrder(int productsSortOrder) {
        this.productsSortOrder = productsSortOrder;
    }
    public int getProductsIsSync() {
        return this.productsIsSync;
    }
    
    public void setProductsIsSync(int productsIsSync) {
        this.productsIsSync = productsIsSync;
    }
    public String getProductsYmName() {
        return this.productsYmName;
    }
    
    public void setProductsYmName(String productsYmName) {
        this.productsYmName = productsYmName;
    }
    public String getProductsBundle() {
        return this.productsBundle;
    }
    
    public void setProductsBundle(String productsBundle) {
        this.productsBundle = productsBundle;
    }
    public int getProductsDfg() {
        return this.productsDfg;
    }
    
    public void setProductsDfg(int productsDfg) {
        this.productsDfg = productsDfg;
    }
    public int getProductsIsExt() {
        return this.productsIsExt;
    }
    
    public void setProductsIsExt(int productsIsExt) {
        this.productsIsExt = productsIsExt;
    }
    public int getAltDescriptionStatus() {
        return this.altDescriptionStatus;
    }
    
    public void setAltDescriptionStatus(int altDescriptionStatus) {
        this.altDescriptionStatus = altDescriptionStatus;
    }
    public boolean isProductAvailable() {
        return this.productAvailable;
    }
    
    public void setProductAvailable(boolean productAvailable) {
        this.productAvailable = productAvailable;
    }
    public String getProductsLogotype() {
        return this.productsLogotype;
    }
    
    public void setProductsLogotype(String productsLogotype) {
        this.productsLogotype = productsLogotype;
    }
    public boolean isProductsHot() {
        return this.productsHot;
    }
    
    public void setProductsHot(boolean productsHot) {
        this.productsHot = productsHot;
    }
    public Boolean getProductsDefend() {
        return this.productsDefend;
    }
    
    public void setProductsDefend(Boolean productsDefend) {
        this.productsDefend = productsDefend;
    }
    public Integer getProductsKit() {
        return this.productsKit;
    }
    
    public void setProductsKit(Integer productsKit) {
        this.productsKit = productsKit;
    }




}


