package Pojo;
// Generated 05.04.2010 14:56:34 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Value generated by hbm2java
 */
public class Value implements java.io.Serializable {

    private Integer valueId;
    private String valueName;
    private String valueAlternative;
    private List<Attribute> attributes = new ArrayList(0);

    public Value() {
    }

    public Value(String valueName, String valueAlternative, List<Attribute> attributes) {
        this.valueName = valueName;
        this.valueAlternative = valueAlternative;
        this.attributes = attributes;
    }

    public Integer getValueId() {
        return this.valueId;
    }

    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    public String getValueName() {
        return this.valueName;
    }

    public void setValueName(String valueName) {
        this.valueName = valueName;
    }

    public String getValueAlternative() {
        return this.valueAlternative;
    }

    public void setValueAlternative(String valueAlternative) {
        this.valueAlternative = valueAlternative;
    }

    public List<Attribute> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
        this.attributes = attributes;
    }
}


