package pojo;
// Generated 30.12.2009 13:21:25 by Hibernate Tools 3.2.1.GA

/**
 * Keyhtml generated by hbm2java
 */
public class Keyhtml implements java.io.Serializable {

    private Integer id;
    private String keyarticle;
    private String keyhtml;

    public Keyhtml() {
    }

    public Keyhtml(String keyarticle, String keyhtml) {
        this.keyarticle = keyarticle;
        this.keyhtml = keyhtml;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getKeyarticle() {
        return this.keyarticle;
    }

    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }

    public String getKeyhtml() {
        return this.keyhtml;
    }

    public void setKeyhtml(String keyhtml) {
        this.keyhtml = keyhtml;
    }
}


