package pojo;
// Generated 26.12.2009 18:03:07 by Hibernate Tools 3.2.1.GA

/**
 * Keymarketing generated by hbm2java
 */
public class Keymarketing implements java.io.Serializable {

    private Integer id;
    private String keyarticle;
    private String keymarketing;

    public Keymarketing() {
    }

    public Keymarketing(String keyarticle, String keymarketing) {
        this.keyarticle = keyarticle;
        this.keymarketing = keymarketing;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getKeyarticle() {
        return this.keyarticle;
    }

    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }

    public String getKeymarketing() {
        return this.keymarketing;
    }

    public void setKeymarketing(String keymarketing) {
        this.keymarketing = keymarketing;
    }

    @Override
    public String toString() {
        return getKeymarketing();
    }
}


