package pojo;
// Generated 28.12.2009 12:09:19 by Hibernate Tools 3.2.1.GA



/**
 * Keywarranty generated by hbm2java
 */
public class Keywarranty  implements java.io.Serializable {


     private Integer id;
     private String keyarticle;
     private String keywarranty;

    public Keywarranty() {
    }

    public Keywarranty(String keyarticle, String keywarranty) {
       this.keyarticle = keyarticle;
       this.keywarranty = keywarranty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getKeyarticle() {
        return this.keyarticle;
    }
    
    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }
    public String getKeywarranty() {
        return this.keywarranty;
    }
    
    public void setKeywarranty(String keywarranty) {
        this.keywarranty = keywarranty;
    }




}


