package pojo;
// Generated 25.12.2009 17:07:14 by Hibernate Tools 3.2.1.GA



/**
 * Matching generated by hbm2java
 */
public class Matching  implements java.io.Serializable {


     private int id;
     private String keyarticle;
     private String vendorarticle;

    public Matching() {
    }

    public Matching(int id) {
        this.id = id;
    }

    public Matching(int id, String keyarticle, String vendorarticle) {
        this.id = id;
        this.keyarticle = keyarticle;
        this.vendorarticle = vendorarticle;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getKeyarticle() {
        return this.keyarticle;
    }

    public void setKeyarticle(String keyarticle) {
        this.keyarticle = keyarticle;
    }
    public String getVendorarticle() {
        return this.vendorarticle;
    }
    
    public void setVendorarticle(String vendorarticle) {
        this.vendorarticle = vendorarticle;
    }




}


