package pojo;
// Generated 18.01.2010 11:45:51 by Hibernate Tools 3.2.1.GA



/**
 * NixInputData generated by hbm2java
 */
public class NixInputData  implements java.io.Serializable {


     private long id;
     private String productType;
     private String productUrl;
     private String htmlData;

    public NixInputData() {
    }

	
    public NixInputData(long id) {
        this.id = id;
    }
    public NixInputData(long id, String productType, String productUrl, String htmlData) {
       this.id = id;
       this.productType = productType;
       this.productUrl = productUrl;
       this.htmlData = htmlData;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getProductUrl() {
        return this.productUrl;
    }
    
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }
    public String getHtmlData() {
        return this.htmlData;
    }
    
    public void setHtmlData(String htmlData) {
        this.htmlData = htmlData;
    }




}


