package pojo;
// Generated 18.01.2010 11:45:51 by Hibernate Tools 3.2.1.GA



/**
 * NixOutputData generated by hbm2java
 */
public class NixOutputData  implements java.io.Serializable {


     private long id;
     private String fullName;
     private String manufacturer;
     private String article;
     private String productType;
     private String picUrl;
     private String groupe;
     private String attribute;
     private String attributeValue;

    public NixOutputData() {
    }

	
    public NixOutputData(long id) {
        this.id = id;
    }
    public NixOutputData(long id, String fullName, String manufacturer, String article, String productType, String picUrl, String groupe, String attribute, String attributeValue) {
       this.id = id;
       this.fullName = fullName;
       this.manufacturer = manufacturer;
       this.article = article;
       this.productType = productType;
       this.picUrl = picUrl;
       this.groupe = groupe;
       this.attribute = attribute;
       this.attributeValue = attributeValue;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getPicUrl() {
        return this.picUrl;
    }
    
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }
    public String getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(String groupe) {
        this.groupe = groupe;
    }
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }




}


