package Pojo;
// Generated 15.10.2009 12:44:11 by Hibernate Tools 3.2.1.GA



/**
 * Pt generated by hbm2java
 */
public class Pt  implements java.io.Serializable {


     private int id;
     private String productType;

    public Pt() {
    }

	
    public Pt(int id) {
        this.id = id;
    }
    public Pt(int id, String productType) {
       this.id = id;
       this.productType = productType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }




}


